Add new data and transactions
JakariaJishan/Vet-clinic-database pull request #3
Opened 2023-04-04 20:47 UTC by JakariaJishan

2023-04-04 21:12 UTC, danmainah requested changes
Hi @, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ Gitflow was correctly used
✔️  Good design

# Required Changes ♻️

- [x] @JakariaJishan kindly add screenshots for all your queries you only have 3 screenshots and the second one is wrong kindly repeat it(this was caused by you changing the data values)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-04-04 21:12 UTC, danmainah commented on schema.sql
> +	species char(50)
- [x] @JakariaJishan great work adding a new column but you did it wrong, you are required to use SQL commands to make changes in your table, in this case, you should use the `ALTER TABLE` command to add the new column, also the column should be of type varchar since its a string.

2023-04-04 21:12 UTC, danmainah commented on data.sql
> +values ('Boarmon','07-11-2005',7,true,20.4);
- [x] @JakariaJishan kindly check on your date it's not correct, kindly rectify the month from 11 to 6

2023-04-04 21:12 UTC, danmainah commented on data.sql
> +values ('Angemon','12-06-2005',1,true,45);
- [ ] @JakariaJishan you are not supposed to change the figures of your weight, kindly return the negative weights as per the project requirement,

2023-04-04 21:12 UTC, danmainah commented on queries.sql
> +
- [ ] @JakariaJishan kindly add a query to change the species column to unspecified and rollback the change, while at it kindly don't forget to add a query to verify the change was done before rollback and a query to verify the change was undone
![image](https://user-images.githubusercontent.com/61408860/229921413-ac9ba689-c7e0-4884-a639-8fac24935177.png)

2023-04-04 21:12 UTC, danmainah commented on queries.sql
> +
- [ ] @JakariaJishan kindly add a query to verify the change was made, also add a commit to the transaction and then add another query to verify the change persisted after commit
![image](https://user-images.githubusercontent.com/61408860/229922220-03acd5df-a357-4ae3-b390-ea7652a0b981.png)

2023-04-04 21:12 UTC, danmainah commented on queries.sql
> +rollback
- [ ] @JakariaJishan kindly add query before rollback to verify that change was madeand after the rollback to verify that change was undone.

2023-04-05 16:03 UTC, danmainah requested changes
Hi @JakariaJishan , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ Gitflow was correctly used
✔️ Good design

 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 16:03 UTC, danmainah commented on data.sql
> +values ('Boarmon','2005-11-07',7,true,20.4);
- [x] @JakariaJishan as previously suggested kindly change the date in Boarmon from 2005-11-07 to the correct figure 2005-06-07.

2023-04-05 16:03 UTC, danmainah commented on data.sql
> +values ('Angemon','2005-06-12',1,true,45);
- [x] @JakariaJishan as previously requested kindly return the negative weights of animals as they are in the project requirement.

2023-04-05 16:03 UTC, danmainah commented on queries.sql
> +
- [x] @JakariaJishan as previously requested kindly add a query before and after the commit, to verify changes were made before the commit and the changes persisted after the commit.

2023-04-05 16:03 UTC, danmainah commented on queries.sql
> +
- [x] @JakariaJishan great job implementing the changes requested however you have not added a query to verify that the change was undone after rollback.

2023-04-05 16:03 UTC, danmainah commented on queries.sql
> +
- [ ] @JakariaJishan great work implementing the changes requested however you still haven't added a screenshot for this transaction

2023-04-05 16:56 UTC, JakariaJishan commented on queries.sql
> +
@danmainah select * from animals; it is the query?

2023-04-05 17:36 UTC, bobb-Rob requested changes
## STATUS: CHANGES REQUIRED ♻️

Hi @JakariaJishan, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/34482800e1b92cb79ddca06edb4051edc407cb190f896e1e949e596aa9073851/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f556461535559436c723932636a57706556782f67697068792e676966)

 ## Highlights
✅ Correct use of GitHub flow
✅ Very descriptive Pull Request(PR)



 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 17:36 UTC, bobb-Rob commented on data.sql
> +values ('Ditto','2022-05-14',4,true,-22);
- [ ] You did well changing the data values to the correct ones based on the project requirement. But it appears you introduced some error in the `weight_kg` value of `Boarmon`, `Blossom`, and `Ditto`. These ones are not negative values as you have made here. Kindly correct.

2023-04-05 17:49 UTC, Munsa1 approved these changes
Hi @JakariaJishan, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Made Previously requested changes :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 17:53 UTC, merged